import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google"; // Import fonts
import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";
import bgImage from "./assests/hero-bg.jpg";

// Load fonts with Latin subset
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          backgroundImage: `linear-gradient(rgba(239, 35, 60, 0.95), rgba(239, 35, 60, 0.95)), url(${bgImage.src})`,
          backgroundSize: "cover",
          backgroundPosition: "center",
          backgroundRepeat: "no-repeat",
        }}
        className={`${inter.variable} ${robotoMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <Header />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
